services:
    #Our PostgreSQL database
  db:
    #The Docker image of postgres -- we're using the latest.
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprod!

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080